
server:
  port: 9003

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 172.20.10.11:8848 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'




