###consul服务端口号
server:
  port: 4020

spring:
  application:
    name: cloud-consumer-order
  ####consul注册中心地址
  cloud:
    consul:
      host: 172.20.10.11
      port: 8500
      discovery:
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}
